/**
 * One-time data migration: Prisma Postgres → Cloudflare D1
 *
 * Run with:
 *   node scripts/migrate-to-d1.js
 *
 * This reads every table from the old PostgreSQL database and writes a
 * D1-compatible SQL file (migration-data.sql) that you then apply with:
 *   wrangler d1 execute modern-db --file=scripts/migration-data.sql
 */

const { Client } = require("pg");
const fs = require("fs");
const path = require("path");

const OLD_DATABASE_URL =
  "postgres://a1c0c6def41c6f5c533cf2db56dfb0cd3141ef2b3ccc8f32aaf5b3ac2e77ae8e:sk_ydgxlCz-ZBW6PTSYVtwst@db.prisma.io:5432/postgres?sslmode=require";

// Tables in insertion order (parents before children)
const TABLES = [
  "stores",
  "site_settings",
  "navigation_links",
  "hero_slides",
  "hero_side_cards",
  "trust_features",
  // Categories: first pass inserts all rows with parent_id = NULL,
  // second pass restores parent_id so the FK is never violated.
  "categories",
  "home_category_groups",
  "home_category_group_items",
  "profiles",
  "products",
  "product_media",
  "product_variants",
  "product_specs",
  "product_bullets",
  "product_relations",
  "reviews",
  "wishlists",
  "wishlist_items",
];

/** Escape a single value for a SQLite INSERT statement */
function sqliteValue(value, pgType) {
  if (value === null || value === undefined) return "NULL";

  // Booleans → 1 / 0
  if (typeof value === "boolean") return value ? "1" : "0";

  // Numbers → bare number
  if (typeof value === "number") return String(value);

  // Dates / timestamps → ISO string
  if (value instanceof Date) return `'${value.toISOString().replace(/'/g, "''")}'`;

  // Objects (jsonb) → JSON string
  if (typeof value === "object") return `'${JSON.stringify(value).replace(/'/g, "''")}'`;

  // Everything else (strings, UUIDs, enums, decimals-as-strings) → quoted string
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Build an INSERT statement for one row */
function buildInsert(table, row, columns) {
  const cols = columns.map((c) => `"${c.name}"`).join(", ");
  const vals = columns.map((c) => sqliteValue(row[c.name], c.dataTypeID)).join(", ");
  return `INSERT OR IGNORE INTO "${table}" (${cols}) VALUES (${vals});`;
}

async function main() {
  const client = new Client({
    connectionString: OLD_DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();
  console.log("Connected to Postgres.");

  const lines = [
    "-- D1 data migration generated by scripts/migrate-to-d1.js",
    `-- Generated: ${new Date().toISOString()}`,
    "",
    "PRAGMA foreign_keys = OFF;",
    "",
  ];

  for (const table of TABLES) {
    console.log(`Exporting ${table}...`);

    let result;
    try {
      if (table === "categories") {
        // First pass: insert all rows with parent_id forced to NULL
        result = await client.query(`SELECT * FROM "${table}" ORDER BY created_at ASC`);
      } else {
        result = await client.query(`SELECT * FROM "${table}" ORDER BY created_at ASC`);
      }
    } catch (err) {
      // Table might not exist yet (empty DB)
      console.warn(`  Skipping ${table}: ${err.message}`);
      continue;
    }

    if (result.rows.length === 0) {
      console.log(`  (empty)`);
      continue;
    }

    lines.push(`-- ${table} (${result.rows.length} rows)`);

    if (table === "categories") {
      // Pass 1: insert without parent_id
      const columnsNoParent = result.fields.map((f) => f.name).filter((n) => n !== "parent_id");
      for (const row of result.rows) {
        const subRow = { ...row, parent_id: null };
        const cols = result.fields.filter((f) => f.name !== "parent_id");
        lines.push(buildInsert(table, subRow, cols));
      }

      // Pass 2: restore parent_id
      lines.push(`-- restore category parent_id links`);
      for (const row of result.rows) {
        if (row.parent_id) {
          lines.push(
            `UPDATE "categories" SET "parent_id" = '${row.parent_id}' WHERE "id" = '${row.id}';`
          );
        }
      }
    } else {
      for (const row of result.rows) {
        lines.push(buildInsert(table, row, result.fields));
      }
    }

    lines.push("");
  }

  lines.push("PRAGMA foreign_keys = ON;");
  lines.push("");

  await client.end();

  const outPath = path.join(__dirname, "migration-data.sql");
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");

  const totalRows = lines.filter((l) => l.startsWith("INSERT")).length;
  console.log(`\nDone! ${totalRows} INSERT statements written to scripts/migration-data.sql`);
  console.log("\nNext steps:");
  console.log("  1. Create your D1 database (if you haven't already):");
  console.log("       wrangler d1 create modern-db");
  console.log("  2. Apply the schema:");
  console.log("       npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script | wrangler d1 execute modern-db --file=-");
  console.log("  3. Load the exported data:");
  console.log("       wrangler d1 execute modern-db --file=scripts/migration-data.sql");
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
